steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build',
      '--build-arg', 'BUILD_VERSION=${_VERSION}',
      '-t', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:${_VERSION}',
      '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:${_VERSION}']
